on:
  schedule:
    - cron: '0 */3 * * *'
  workflow_dispatch:
  pull_request:
    branches:
      - master
name: Test
permissions:
  contents: read

env:
  FORESIGHT_UPLOADER_SIGNER_URL: https://upload.service.runforesight.us
  WORKFLOW_TELEMETRY_BASE_URL: https://api.service.runforesight.us

jobs:
  go-versions:
    runs-on: ubuntu-latest
    outputs:
      versions: ${{ steps.versions.outputs.value }}
    steps:
      - id: versions
        run: |
          versions=$(curl -s 'https://go.dev/dl/?mode=json' | jq -c 'map(.version[2:])')
          echo "::set-output name=value::${versions}"
  test_v3_module:
    needs: go-versions
    strategy:
      fail-fast: false
      matrix:
        go-version: ${{fromJson(needs.go-versions.outputs.versions)}}
        os: [ubuntu-20.04, ubuntu-18.04, windows-2019, macos-11]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Collect Workflow Telemetry
      if: always()
      uses: runforesight/foresight-workflow-kit-action@v1
      with:
        api_key: ${{ secrets.FORESIGHT_PROJECT_WALL_APIKEY }}
    - name: Install Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v3
    - id: go-env
      run: |
        echo "::set-output name=cache::$(go env GOCACHE)"
        echo "::set-output name=mod-cache::$(go env GOMODCACHE)"
    - name: Cache go modules
      uses: actions/cache@v3
      with:
        path: |
          ${{ steps.go-env.outputs.cache }}
          ${{ steps.go-env.outputs.mod-cache }}
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: ${{ runner.os }}-go-
    - name: Test
      run: |
        go test -v -json -coverprofile='coverage.out' -covermode=atomic ./... > ./test-report.json

    - name: Analyze Test and/or Coverage Results
      if: always()
      uses: runforesight/foresight-test-kit-action@v1
      with:
        api_key: ${{ secrets.FORESIGHT_PROJECT_WALL_APIKEY }}
        test_framework: golang
        test_format: json
        test_path: ./test-report.json
        coverage_format: golang
        coverage_path: |
            coverage.out
